#!/usr/bin/env bash

######################################################################
# This script installs required dependencies for texture_nets
######################################################################
{

luarocks install cutorch
luarocks install display
luarocks install loadcaffe

# Done.
echo "==> texture_nets dependencies have been installed"

}
